

services:
  client:
    build: ./Client
    ports:
      - "3005:80"
    restart: unless-stopped
    depends_on:
      - server
    networks:
      - app-network

  server:
    build: ./Server
    ports:
      - "3004:3002"
    env_file: .env
    environment:
      NODE_ENV: development
      DB_URL: ${DB_URL}
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
